// <auto-generated />
namespace PetGrooming.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _30January : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30January));
        
        string IMigrationMetadata.Id
        {
            get { return "202001302307379_30January"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
